## List of 50 commonly used numpy methods and attributes

#### by

### Saud Qadir Khan (PIAIC97528)


### Numpy version

In [1]:
import numpy as np
print (np.__version__)

1.19.1


1. Creation of array in numpy

In [2]:
small_array= np.arange(1,10)
my_array = np.arange(1,100000)
small_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Numpy is super fast

In [3]:
%time for _ in range(10): my_array = my_array*2

Wall time: 6 ms


In [4]:
my_list = list(range((100000)))
%time for _ in range(10): my_list = [x*2 for x in my_list]

Wall time: 476 ms


2. Multidimension Random Number

In [5]:
multi_random = np.random.randn(4,3)
multi_random

array([[ 2.244796  ,  0.71093245,  0.06954277],
       [-0.76999445,  0.38521397, -0.27958527],
       [-0.868475  , -0.74563508, -0.51254754],
       [ 0.19162284,  0.26669074, -0.69145862]])

3. Array from list

In [6]:
list_of_list = [[1,2,3,4],[5,6,7,8],[10,11,12,13]] 
array_from_list = np.array(list_of_list, dtype = object)
array_from_list

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [10, 11, 12, 13]], dtype=object)

Size of each list must be same otherwise it will create 1-d array containing list, look at number of items in 2nd list

In [7]:
list_of_list = [[1,2,3,4],[5,6,7,8,10],[10,11,12,13]] 
array_from_list_2 = np.array(list_of_list, dtype = object)
array_from_list_2

array([list([1, 2, 3, 4]), list([5, 6, 7, 8, 10]), list([10, 11, 12, 13])],
      dtype=object)

4. Dimensions
5. Shape
6. Type

In [8]:
print("Dimesion of the array is ", array_from_list.ndim)
print("Shape of the array is ", array_from_list.shape)
print("Type of the array is ", array_from_list.dtype)

Dimesion of the array is  2
Shape of the array is  (3, 4)
Type of the array is  object


7. -11. Other ways of creating an array

In [9]:
np.zeros((4,3)) # full of zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4,4)) # full of 1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.eye(4,4) # identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
np.full((4,3),"full") # array with custom fill

array([['full', 'full', 'full'],
       ['full', 'full', 'full'],
       ['full', 'full', 'full'],
       ['full', 'full', 'full']], dtype='<U4')

In [13]:
np.empty((4,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

12. Convert the data type

In [14]:
print(small_array)
print("original data type: ",small_array.dtype)
print("Now modifying data type........")
small_array=small_array.astype(np.float64)
print(small_array)
print("new data type: ",small_array.dtype)
print("Now modifying data type again........")
small_array=small_array.astype(np.int32)
print("new data type: ",small_array.dtype)
print(small_array)

[1 2 3 4 5 6 7 8 9]
original data type:  int32
Now modifying data type........
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
new data type:  float64
Now modifying data type again........
new data type:  int32
[1 2 3 4 5 6 7 8 9]


13. Arithmetic Operation with NumPy Arrays

In [15]:
small_array * small_array

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [16]:
small_array - small_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
small_array + small_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [18]:
1 / small_array

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111])

In [19]:
small_array**0.5

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

14. compare two array

In [20]:
small_array_2 = np.array([9,4,8,7,5,1,6,2,3])
small_array<small_array_2

array([ True,  True,  True,  True, False, False, False, False, False])

15. extract elements that satisfies the condition

In [21]:
small_array[small_array%2==0]

array([2, 4, 6, 8])

16. Indexing and Slicing in Numpy

In [22]:
#6th,7th and 8th index of small_array
small_array[5:8]

array([6, 7, 8])

In [23]:
#item from 1st row and 4th column
array_from_list[0,3]

4

17. Facny Indexing in Numpy

In [24]:
small_array[[5,1,2,3]]

array([6, 2, 3, 4])

18. Resahpe an array

In [25]:
print("Original Shape: ", small_array.shape)
new_small_array = small_array.reshape((3,3),order='A') #order ='R' for row wise arraging
print("New Shape: ", new_small_array.shape)
new_small_array

Original Shape:  (9,)
New Shape:  (3, 3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

19. Transposing an array

In [26]:
new_small_array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

20. matrix multiplication

In [27]:
np.dot(new_small_array,new_small_array.T)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])

21. Element wise Square Root

In [28]:
np.sqrt(small_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

22. Element wise exp

In [29]:
np.exp(small_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

23. Maximum in an array
24. Minimum in an array

In [30]:
print("Maximum Value: ",np.max(small_array))
print("Minimum Value: ",np.min(small_array))

Maximum Value:  9
Minimum Value:  1


25. -28. Element wise Comaprison of 2 arrays

In [31]:
print("Maximum element wise: ", np.maximum(small_array,small_array_2))
print("Minimum element wise: ", np.minimum(small_array,small_array_2))
print("Add element wise: ", np.add(small_array,small_array_2))
print("Multiply element wise: ", np.multiply(small_array,small_array_2))

Maximum element wise:  [9 4 8 7 5 6 7 8 9]
Minimum element wise:  [1 2 3 4 5 1 6 2 3]
Add element wise:  [10  6 11 11 10  7 13 10 12]
Multiply element wise:  [ 9  8 24 28 25  6 42 16 27]


29. Meshgrid

In [32]:
asd= np.array([1,2,3])
asdf= np.array([5,6,7])
np.meshgrid(asd,asdf)

[array([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]),
 array([[5, 5, 5],
        [6, 6, 6],
        [7, 7, 7]])]

30. Conditional Logic

In [33]:
# if small array less than 5 take value from small array otherwise
# take value from small_array_2
np.where(small_array<5,small_array,small_array_2)

array([1, 2, 3, 4, 5, 1, 6, 2, 3])

31. -34. Statistical Methods

In [34]:
print("Mean of array: ", small_array.mean())
print("Sum of array: ", small_array.sum())
print("std of array: ", small_array.std())
print("Cummulative sum: ", small_array.cumsum())

Mean of array:  5.0
Sum of array:  45
std of array:  2.581988897471611
Cummulative sum:  [ 1  3  6 10 15 21 28 36 45]


35. -36. Boolean Array

In [35]:
print("Check if any of item is True:", small_array.any())
print("Check if All of item is True:", small_array.all())

Check if any of item is True: True
Check if All of item is True: True


37. Sorting

In [36]:
random_numbers = np.array([1,5,7,5,64,2,31,54,8,1,-5,0,5])
random_numbers.sort()
random_numbers

array([-5,  0,  1,  1,  2,  5,  5,  5,  7,  8, 31, 54, 64])

38. Unique Elements

In [37]:
np.unique(random_numbers)

array([-5,  0,  1,  2,  5,  7,  8, 31, 54, 64])

39. -40. Intersection and Union

In [38]:
print("Intersection: ",np.intersect1d(small_array,random_numbers))
print("Union: ",np.union1d(small_array,random_numbers))

Intersection:  [1 2 5 7 8]
Union:  [-5  0  1  2  3  4  5  6  7  8  9 31 54 64]


41. -42. Save the data

In [39]:
np.save('only_small_array.npy',small_array)
np.savez('two_array.npz',s_a=small_array,s_r = random_numbers)

43. Load the data

In [40]:
loaded_data = np.load('two_array.npz')
loaded_data['s_a']

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

44. Concatenate two arrays

In [41]:
np.concatenate([small_array, random_numbers])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -5,  0,  1,  1,  2,  5,  5,  5,
        7,  8, 31, 54, 64])

45. Merge two arrays vertically

In [42]:
np.vstack([small_array, small_array_2])

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [9, 4, 8, 7, 5, 1, 6, 2, 3]])

46. Merge two arrays horizontally

In [43]:
np.hstack([small_array, random_numbers])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, -5,  0,  1,  1,  2,  5,  5,  5,
        7,  8, 31, 54, 64])

47. Repeat the sequence

In [44]:
np.repeat(small_array,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 6, 7, 7, 7, 8,
       8, 8, 9, 9, 9])

48. Tile the sequence

In [45]:
np.tile(small_array, 3)

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4,
       5, 6, 7, 8, 9])

49. Clip the values

In [46]:
np.clip(random_numbers, 1,50)

array([ 1,  1,  1,  1,  2,  5,  5,  5,  7,  8, 31, 50, 50])

50. Percentile

In [47]:
np.percentile(random_numbers,[25,50,75,100])

array([ 1.,  5.,  8., 64.])